services:
  contracting-microservice:
    image: carlosclavijo/contracting-webapi:v4
    container_name: contracting-microservice
    ports:
      - "5010:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ContractingDatabaseConnectionString__ConnectionString=Host=postgres_db;Port=5432;Database=contracting;Username=postgres;Password=abc12345;Include Error Detail=true
      - RabbitMqSettings__Host=rabbitmq
      - RabbitMqSettings__UserName=storeUser
      - RabbitMqSettings__Password=storeUserPassword
      - RabbitMqSettings__VirtualHost=/
    depends_on:
      - db_service
    networks:
      - nur-network
      - kong-net

  db_service:
    image: carlosclavijo/mipostgresql:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc12345
      POSTGRES_DB: contracting
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "contracting"]
      interval: 10s
      retries: 5
      start_period: 20s
    networks:
      - nur-network

networks:
  nur-network:
    external: true
  kong-net:
    external: true
volumes:
  postgres_data: