name: SonarCloud Analysis

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore Contracting.sln

    - name: Build the solution
      run: dotnet build Contracting.sln --no-restore --configuration Release

    - name: Run tests with coverage
      run: |
        dotnet test Contracting.Test/Contracting.Test.csproj \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          --logger "trx"

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Convert cobertura to opencover
      run: |
        reportgenerator \
          -reports:TestResults/**/coverage.cobertura.xml \
          -targetdir:coverage-report \
          -reporttypes:OpenCover

    - name: Run SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: carlosclavijo_Nurtricenter-Contracting
        SONAR_ORGANIZATION: carlosclavijo
        SONAR_SCANNER_OPTS: >
          -Dsonar.cs.opencover.reportsPaths=coverage-report/coverage.opencover.xml
